Add error checking to init role

diff --git a/orchestration/init/script b/orchestration/init/script
--- a/orchestration/init/script
+++ b/orchestration/init/script
@@ -1,7 +1,8 @@
 #!/usr/bin/env sh
 #init - create user, only secure ssh access, install package managers and sudo
-set -eu
+set -u
 
+die() { if [ "$#" -gt 0 ]; then printf "%s" "$*" >&2; fi; exit 1; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 [ $(id -u) = 0 ] && ! exists sudo && sudo() { "$@"; } #just run as root
 rndpasswd() {
@@ -9,40 +10,49 @@ rndpasswd() {
         LC_CTYPE=C tr -cd A-Za-z0-9 \
         | head -c64 \
         | sed p \
-        | sudo passwd "${1:-root}" >/dev/null 2>&1
+        | sudo passwd "${1:-root}" >/dev/null 2>&1 \
+        || die "Can't lock password for ${1:-root}"
 }
 
 #Initialize package managers
 case "$(uname -s)" in
 Darwin)
-    exists brew || ruby -e "$(curl -fsSL \
-        https://raw.githubusercontent.com/Homebrew/install/master/install)"
+    if ! exists brew; then
+        ruby -e "$(curl -fsSL \
+            printf "%s%s" https://raw.githubusercontent.com/Homebrew/
+                install/master/install)" \
+            || die "Homebrew installation failed"
+    fi
     ;;
 Linux)
     if exists pacman; then
-        sudo pacman-key --init
-        sudo pacman-key --populate \
-            "archlinux$([ "$(uname -m)" = aarch64 ] && echo arm)"
+        sudo pacman-key --init \
+            && sudo pacman-key --populate \
+                "archlinux$([ "$(uname -m)" = aarch64 ] && echo arm)" \
+            || die "pacman key initialisation failed"
     fi
     ;;
 esac
 
 #Install zsh
-exists pacman && sudo pacman -q --noconfirm -S --needed zsh
-exists apk && sudo apk -q add zsh
+exists pacman \
+    && { sudo pacman --needed --noconfirm -qS zsh || die "Can't add zsh"; }
+exists apk && { sudo apk -q add zsh || die "Can't add zsh"; }
 
 #Create user
 if ! id -u mil >/dev/null 2>&1; then
     exists useradd && sudo useradd -s "$(command -v zsh)" -G wheel -m mil
     exists adduser && sudo adduser -s "$(command -v zsh)" -G wheel -D mil
+    id -u mil >/dev/null 2>&1 || die "Can't add user mil"
     rndpasswd mil
 fi
 
 #Copy ssh public key
-mkdir -p ~mil/.ssh
-cp init/authorized_keys ~mil/.ssh/authorized_keys
-chown -R mil ~mil/.ssh
-chmod -R og-rwxs ~mil/.ssh
+mkdir -p ~mil/.ssh \
+    && cp init/authorized_keys ~mil/.ssh/authorized_keys \
+    && chown -R mil ~mil/.ssh \
+    && chmod -R og-rwxs ~mil/.ssh \
+    || die "Can't install public key"
 
 #Install and configure sshd
 sudo cp init/sshd_config /etc/ssh/sshd_config
@@ -51,11 +61,12 @@ Darwin)
     sudo systemsetup -f -setremotelogin on
     ;;
 Linux)
+    sudo cp init/sudoers /etc/sudoers || die "Can't configure sudo"
     exists pacman && sudo pacman -q --noconfirm -S --needed openssh sudo
     exists apk && sudo apk add -q openssh sudo
     exists systemctl && sudo systemctl enable --now sshd
     exists systemctl && sudo systemctl reload sshd
-    sudo cp init/sudoers /etc/sudoers
+    exists sudo && ps -A | grep -q sshd || die "sudo/ssh setup failed"
     rndpasswd root
     ;;
 esac
