Make init role compatible with OpenWRT

diff --git a/orchestration/init/script b/orchestration/init/script
--- a/orchestration/init/script
+++ b/orchestration/init/script
@@ -2,7 +2,7 @@
 #init - create user, only secure ssh access, install package managers and sudo
 set -eu
 
-die() { if [ "$#" -gt 0 ]; then printf "%s" "$*" >&2; fi; exit 1; }
+die() { if [ "$#" -gt 0 ]; then printf "%s\n" "$*" >&2; fi; exit 1; }
 exists() { command -v "$1" >/dev/null 2>&1; }
 [ $(id -u) = 0 ] && ! exists sudo && sudo() { "$@"; } || true #just run as root
 rndpasswd() {
@@ -22,7 +22,9 @@ Darwin)
         ruby -e "$(curl -fsSL "$URL")" || die "Homebrew installation failed"
     fi;;
 Linux)
-    if exists pacman; then
+    if exists opkg; then
+        sudo opkg update;
+    elif exists pacman; then
         sudo pacman-key --init
         sudo pacman-key --populate \
             "archlinux$(uname -m | sed -n 's/\(armv7l\|aarch64\)/arm/p')"
@@ -40,9 +42,10 @@ fi
 
 #Create user
 if ! id -u mil >/dev/null 2>&1; then
+    if exists opkg; then sudo opkg install shadow-useradd shadow-groupadd; fi
     if exists useradd; then
         sudo groupadd wheel
-        sudo useradd -s "$(command -v zsh)" -G wheel -m mil
+        sudo useradd -s "$(command -v zsh || command -v ash)" -G wheel -m mil
     elif exists adduser; then
         sudo adduser -s "$(command -v zsh)" -G wheel -D mil
     fi
@@ -53,33 +56,42 @@ fi
 #Copy ssh public key
 mkdir -p ~mil/.ssh
 cp init/authorized_keys ~mil/.ssh/authorized_keys
-chown -R mil ~mil/.ssh
+chown -R mil:mil ~mil/.ssh
 chmod -R og-rwxs ~mil/.ssh
 
-#Install and configure sshd
-sudo cp init/sshd_config /etc/ssh/sshd_config
-case "$(uname -s)" in
-Darwin)
-    sudo systemsetup -f -setremotelogin on
-    ;;
-Linux)
+#Install and configure sshd/dropbear
+if exists uci; then
+    sudo opkg install sudo
     sudo cp init/sudoers /etc/sudoers
-    if exists pacman; then
-        sudo pacman --needed --noconfirm -qS openssh sudo
-        sudo systemctl enable --now sshd
-        sudo systemctl reload sshd
-    elif exists apk; then
-        sudo apk -q add openssh sudo
-    elif exists apt-get; then
-        sudo apt-get install -qy openssh-server sudo
-        sudo systemctl enable --now ssh
-        sudo systemctl reload ssh
-    fi
-    unset -f sudo
-    exists sudo && ps -A | grep -q sshd || die "sudo/ssh setup failed"
-    rndpasswd root
-    ;;
-esac
+    sudo uci set 'dropbear.@dropbear[0].RootPasswordAuth=off'
+    sudo uci set 'dropbear.@dropbear[0].PasswordAuth=off'
+    sudo uci commit dropbear
+    sudo /etc/init.d/dropbear restart
+else
+    sudo cp init/sshd_config /etc/ssh/sshd_config
+    case "$(uname -s)" in
+    Darwin)
+        sudo systemsetup -f -setremotelogin on
+        ;;
+    Linux)
+        sudo cp init/sudoers /etc/sudoers
+        if exists pacman; then
+            sudo pacman --needed --noconfirm -qS openssh sudo
+            sudo systemctl enable --now sshd
+            sudo systemctl reload sshd
+        elif exists apk; then
+            sudo apk -q add openssh sudo
+        elif exists apt-get; then
+            sudo apt-get install -qy openssh-server sudo
+            sudo systemctl enable --now ssh
+            sudo systemctl reload ssh
+        fi
+        unset -f sudo
+        exists sudo && ps -A | grep -q sshd || die "sudo/ssh setup failed"
+        ;;
+    esac
+fi
+rndpasswd root
 
 #Remove set-up user
 if id -u alarm >/dev/null 2>&1; then
@@ -94,6 +106,9 @@ if ! expr localhost = "$HOSTNAME" \| "$HOSTNAME" : '[0-9.]*$' >/dev/null; then
             sudo scutil --set "$name" "$HOSTNAME"
         done
         sudo dscacheutil -flushcache
+    elif exists uci; then
+        sudo uci set "system.@system[0].hostname=$HOSTNAME"
+        sudo uci commit system
     fi
 fi
 
